# Generated by Django 5.2.5 on 2025-09-05 13:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserStyleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kratos_identity_id', models.CharField(max_length=64, unique=True)),
                ('wastedResources', models.CharField(choices=[('allTimes', 'allTimes'), ('oftenTimes', 'oftenTimes'), ('fewTimes', 'fewTimes'), ('never', 'never')], max_length=20)),
                ('feelingSecure', models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('notSure', 'notSure')], max_length=20)),
                ('feelingAnxious', models.CharField(choices=[('struggle', 'struggle'), ('depends', 'depends'), ('rarely', 'rarely'), ('no', 'no')], max_length=20)),
                ('ages', models.CharField(choices=[('18-29', '18-29'), ('30-39', '30-39'), ('40-49', '40-49'), ('50+', '50+')], max_length=10)),
                ('genders', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=10)),
                ('heightUnit', models.CharField(choices=[('cm', 'cm'), ('inch', 'inch')], max_length=10)),
                ('weightUnit', models.CharField(choices=[('lb', 'lb'), ('kg', 'kg')], max_length=10)),
                ('bodyShapes', models.CharField(choices=[('hourglass', 'hourglass'), ('bottomHourglass', 'bottomHourglass'), ('topHourglass', 'topHourglass'), ('spoon', 'spoon'), ('invertedTriangle', 'invertedTriangle'), ('triangle', 'triangle'), ('rectangle', 'rectangle')], max_length=30)),
                ('eyeColors', models.CharField(choices=[('brightBlue', 'brightBlue'), ('lightBlue', 'lightBlue'), ('brightGreen', 'brightGreen'), ('lightGreen', 'lightGreen'), ('gray', 'gray'), ('amber', 'amber'), ('lightHazel', 'lightHazel'), ('darkHazel', 'darkHazel'), ('lightBrown', 'lightBrown'), ('darkBrown', 'darkBrown'), ('mutedBrown', 'mutedBrown'), ('black', 'black')], max_length=20)),
                ('hairColors', models.CharField(choices=[('ashBlonde', 'ashBlonde'), ('goldenBlonde', 'goldenBlonde'), ('ashBrown', 'ashBrown'), ('coolBrown', 'coolBrown'), ('brown', 'brown'), ('warmBrown', 'warmBrown'), ('strawberryBlonde', 'strawberryBlonde'), ('copper', 'copper'), ('auburn', 'auburn'), ('darkAuburn', 'darkAuburn'), ('brownBlack', 'brownBlack'), ('black', 'black')], max_length=20)),
                ('skinTones', models.CharField(choices=[('coolPale', 'coolPale'), ('porcelain', 'porcelain'), ('ivory', 'ivory'), ('peach', 'peach'), ('rosyBeige', 'rosyBeige'), ('neutralBeige', 'neutralBeige'), ('goldenBeige', 'goldenBeige'), ('olive', 'olive'), ('tan', 'tan'), ('bronze', 'bronze'), ('chocolate', 'chocolate'), ('espresso', 'espresso')], max_length=20)),
                ('aestheticStyles', models.CharField(choices=[('casual', 'casual'), ('glam', 'glam'), ('boho', 'boho'), ('romantic', 'romantic'), ('minimalist', 'minimalist'), ('classic', 'classic'), ('street', 'street'), ('preppy', 'preppy'), ('edgy', 'edgy'), ('sporty', 'sporty'), ('Y2K', 'Y2K'), ('eclectic', 'eclectic')], max_length=20)),
                ('goals', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('discoverStyle', 'discoverStyle'), ('feelConfident', 'feelConfident'), ('lookAttractive', 'lookAttractive'), ('spendLess', 'spendLess'), ('saveTime', 'saveTime'), ('other', 'other')], max_length=32), blank=True, default=list, size=None)),
                ('knowingStyles', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('partially', 'partially')], max_length=20, null=True)),
                ('feelingConfident', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('partially', 'partially')], max_length=20, null=True)),
                ('wardrobeWeared', models.CharField(blank=True, choices=[('10%', '10%'), ('25%', '25%'), ('50%', '50%'), ('75%', '75%'), ('90%+', '90%+')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_style_profiles',
                'indexes': [models.Index(fields=['kratos_identity_id'], name='user_style__kratos__dc66ce_idx')],
            },
        ),
    ]
