services:

  django:
    build: .
    container_name: mixoutcore_django
    command: /bin/sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn mixoutcore.wsgi:application --bind 0.0.0.0:8000"
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: mixoutcore.settings
      STATIC_ROOT: /app/staticfiles
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: unless-stopped

  kratos:
    image: oryd/kratos:v1.0.0
    volumes:
      - ./kratos/identity.schema.json:/etc/config/kratos/identity.schema.json:ro
      - ./kratos/registration.jsonnet:/etc/config/kratos/registration.jsonnet:ro
      - ./kratos/kratos.yml:/etc/config/kratos/kratos.yml:ro
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    ports:
      - "4433:4433"
      - "4434:4434"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:4434/health/ready >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
    restart: unless-stopped